export const FETCH_STUDENT = 'FETCH_STUDENT';
export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_TEACHER_CLICKED = 'FETCH_TEACHER_CLICKED';
export const FETCH_AVAILABILITY = 'FETCH_AVAILABILITY';
export const FETCH_ADD_AVAILABILITY = 'FETCH_ADD_AVAILABILITY';
